// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthSchema from "src/models/drizzle/auth.model";
import * as TransactionsSchema from "src/models/drizzle/transactions.model";

const schema = {
	...AuthSchema,
	...TransactionsSchema
};

export default schema;
