// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthSchema from '../models/drizzle/auth.model';
import * as TransactionsSchema from '../models/drizzle/transactions.model';

const schema = {
	...AuthSchema,
	...TransactionsSchema,
};

export default schema;
