// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthSchema from "../models/drizzle/auth.model";
import * as CurrencySchema from "../models/drizzle/currency.model";
import * as EnumSchema from "../models/drizzle/enum.model";
import * as HistorySchema from "../models/drizzle/history.model";
import * as MediaSchema from "../models/drizzle/media.model";
import * as RelationSchema from "../models/drizzle/relation.model";
import * as TemplateSchema from "../models/drizzle/template.model";
import * as TransactionsSchema from "../models/drizzle/transactions.model";

const schema = {
	...AuthSchema,
	...CurrencySchema,
	...EnumSchema,
	...HistorySchema,
	...MediaSchema,
	...RelationSchema,
	...TemplateSchema,
	...TransactionsSchema
};

export default schema;
